- modules/secure-bucket/main.tf
since mfa_delete can't be enabled via Terraform at this moment.
https://github.com/terraform-providers/terraform-provider-aws/issues/629
> fix: temporarily disable mfa_delete on secure buckets

- README.md
- compliance.md
- config_baselines.tf
- modules/config-baseline/main.tf
It enables the following two rules.
- A rule to monitor the MFA setting of root account
- A rule to monitor unrestricted common port in Security Group
rules.
> feat: enable AWS Config rules for monitoring

- config_baselines.tf
aws_config_config_rule should be created after aws_config_configuration_recorder as stated below.
https://www.terraform.io/docs/providers/aws/r/config_config_rule.html
> fix: create a global rule after recorders.

- README.md
- main.tf
- modules/cloudtrail-baseline/README.md
- modules/cloudtrail-baseline/main.tf
- modules/cloudtrail-baseline/variables.tf
- variables.tf
- vpc_baselines.tf
To reduce costs.
- VPC Logs can be manually archived to S3 if needed
- Cloudtrail logs are already mirrored to S3
> Allow setting logs retention in log groups

- modules/vpc-baseline/main.tf
Ignore "subnet_ids" changes instead of associating the default network ACL with the default subnet.
refs #17
> fix: Change how to workaround the default ACL issue.

- compliance.md
- config_baselines.tf
Add more managed config rules for CIS benchmark compliance.
Newly supported CIS items are
- 1.2: Ensure multi-factor authentication (MFA) is enabled for all IAM users that have a console password.
- 1.3: Ensure credentials unused for 90 days or greater are disabled.
- 1.4: Ensure access keys are rotated every 90 days or less.
- 1.12: Ensure no root account access key exists.
- 1.13: Ensure MFA is enabled for the "root" account.
- 1.14: Ensure hardware MFA is enabled for the "root" account.
- 1.16: Ensure IAM policies are attached only to groups or roles.
- 1.22: Ensure IAM policies that allow full "\*:\*" administrative privileges are not created.
> feat: enable managed config rules for benchmark compliance

- modules/vpc-baseline/README.md
- modules/vpc-baseline/main.tf
- modules/vpc-baseline/variables.tf
- vpc_baselines.tf
log_group_name has been deprecated so I replaced them all with log_destination and updated the calling modules and variables as required.
> change from log_group_name to log_destination

- modules/vpc-baseline/main.tf
It seems AWS does not create a default subnet when they add a new
availability zone, causing "Default subnet not found" error.
> fix: remove a default subnet resource

- modules/alarm-baseline/main.tf
Adding all these alarms leaves them in unknown status if there is no status read out when missing (Config rules don't fire all the time, only on event). It's better to just have them on 'good' rather than breaching, no? It defaults to missing.
Adding `treat_missing_data` to the aws_cloudwatch_metric_alarm resolves this as per this MR.
https://www.terraform.io/docs/providers/aws/r/cloudwatch_metric_alarm.html#treat_missing_data
> Change alarm status breach status

- examples/root-example/variables.tf
- main.tf
- modules/secure-bucket/main.tf
- modules/secure-bucket/variables.tf
- variables.tf
force_destroy flag defaults to false since the accidental deletion of audit logs might be
unacceptable in highly secured environments.
fixes #48
> feat: add a flag to enable force_destroy on S3 buckets

- config_baselines.tf
This module creates an AWS Config rule called `AccessKeyRotated`. This rule works fine, but the module also unconditionally enables Security Hub, which already autobootstraps an undeletable rule with `securityhub-access-keys-rotated` that ostensibly does exactly the same thing.
This means that every resource in this category is "counted" twice, which skews the overall statistics in that it essentially doubles the weight of these resources.
> Remove duplicate rule for checking Access Key Rotation and root MFA

- bucket.tf
> fix: do not read AWS Organization when account_type is set to "individual"

- modules/secure-bucket/main.tf
Default secure-bucket module to `sse_algorithm = "AES256"`
fixes nozaq/terraform-aws-secure-baseline/issues/77
> Enable bucket server side encryption for local buckets

- main.tf
- modules/cloudtrail-baseline/main.tf
- modules/cloudtrail-baseline/outputs.tf
- modules/cloudtrail-baseline/variables.tf
- outputs.tf
- variables.tf
This creates and outputs an sns topic attached to the cloudtrail so that it could be used to feed the trail into a queue.
That would allow the trail to be integrated with external logging tools that need to fetch events from an sqs queue (in our case we use this to create an sqs for our graylog server).
It does not affect any of the existing modules functionality.
Please let me know if more clarification is needed for the purpose of this PR. :))
> Output sns topic where cloudtrail publishes events

- bucket.tf
- variables.tf
For example if you have roles in other AWS Accounts you want to grant
access to the logs
> Allows attaching custom policy to the audit logs bucket

- README.md
- main.tf
- modules/cloudtrail-baseline/README.md
- modules/cloudtrail-baseline/main.tf
- modules/cloudtrail-baseline/outputs.tf
- modules/cloudtrail-baseline/variables.tf
- variables.tf
Because we have a very AWS Lambda heavy workload, delivery to a Cloudwatch Logs generates a lot of costs. We don't need the logs, because the central S3 is enough. This PR makes both Cloudwatch Logs and SNS delivery optional (with the default remaining the same).
> Make delivery of CloudTrail to CloudWatch Logs and SNS optional

- config_baselines.tf
PubObjectAcl permission is required when AWS Config accesses the writability check file.
> fix: prevent AWS Config to fire alarms

- modules/vpc-baseline/main.tf
- modules/vpc-baseline/outputs.tf
- modules/vpc-baseline/variables.tf
- outputs.tf
- variables.tf
- vpc_baselines.tf
Address nozaq#144
- vpc_log_destination_type defaults to CW to avoid breaking existing deployments
- if S3 is used, bucket creation is outside the scope of this module
- also addresses issue where IAM Role was created even if VPC flow logs were not enabled
> Add option to publish VPC Flow Logs to either S3 or CW

- main.tf
- modules/cloudtrail-baseline/outputs.tf
Fixes: 
```
Error: Attempt to get attribute from null value
on .terraform/modules/security/main.tf line 70, in module "alarm_baseline":
70:   cloudtrail_log_group_name = local.is_cloudtrail_enabled ? module.cloudtrail_baseline.log_group.name : ""
|----------------
| module.cloudtrail_baseline.log_group is null
```
Module:
```hcl-terraform
module "security" {
source = "nozaq/secure-baseline/aws"
account_type = "individual"
aws_account_id = data.aws_caller_identity.current.account_id
#master_account_id = data.terraform_remote_state.master.outputs.account_id # Future
audit_log_bucket_name = module.logs-edge.id 
use_external_audit_log_bucket = true
cloudtrail_s3_key_prefix = ""
vpc_flow_logs_s3_key_prefix = ""
config_s3_bucket_key_prefix = ""
config_delivery_frequency = "TwentyFour_Hours" …
```
> fix: edge case when not logging to cloudwatch

- examples/organization/master/main.tf
In order to setup an organization analyzer, `access-analyzer.amazonaws.com` must be added as a trusted service principal.  Otherwise, setup fails with error noted in #166.
(ref: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/accessanalyzer_analyzer)
> Enable access analyzer in organization example

- README.md
- config_baselines.tf
- variables.tf
The default configuration for SecurityHub and related AWS/CIS/PCI benchmarks expect to find global resource recording in each region - and all get rather unhappy if it's not there.  SecurityHub, specifically, complains that AWS Config is not setup properly.  
Guidance from AWS on this:
* They enable global recording in all regions with their provided tooling: https://github.com/awslabs/aws-securityhub-multiaccount-scripts
* Note this as a best practice here (item 2): https://aws.amazon.com/blogs/security/nine-aws-security-hub-best-practices/
* Recommend conditionally disabling several controls in non-primary regions (see https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-prereq-config.html#config-resource-recording) if only recording global resources in a single region. …
> Add flag to allow recording global resource config in all regions

- analyzer_baselines.tf
- config_baselines.tf
- ebs_baselines.tf
- guardduty_baselines.tf
- outputs.tf
- securityhub_baselines.tf
- variables.tf
- versions.tf
- vpc_baselines.tf
This PR is enabling new generally available region `ap-northeast-3` (Osaka) and updating minimum version of AWS provider
> Add/Enable ap-northeast-3 (Osaka) region

- README.md
- variables.tf
- vpc_baselines.tf
Hello, 
I added a variable that allows to disable vpc-baseline submodule. We use the default VPC and we can't just wipe out the route table and NACL.
Also regarding the [aws documentation](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-2.9) it should be enough to enable the flow log only for packet rejects and the traffic_type is hardcoded to ALL in the submodule.
Thank you for publishing this module, it really helped a lot with setting up the alarms required by CIS benchmark.
> feat: add vpc_enable variable

- main.tf
- variables.tf
This PR will enable the use of the changes in https://github.com/nozaq/terraform-aws-secure-baseline/pull/164 (control individual alarms).
I forgot to add them to the original PR. Apologies.
> fix: allow alarm variables to be set at top level module

- main.tf
- modules/cloudtrail-baseline/main.tf
- modules/cloudtrail-baseline/variables.tf
- variables.tf
Hello
I added variable `cloudtrail_insight_selector_type` where you can set insight_selector type to `ApiCallRateInsight` which is so far the only value that is accepted as is documented in [official terraform documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail#insight_selector). 
Default value is set to `null`.
> feat: add cloudtrail insight selector type specification

- README.md
- main.tf
- modules/alarm-baseline/README.md
- modules/analyzer-baseline/README.md
- modules/cloudtrail-baseline/README.md
- modules/cloudtrail-baseline/main.tf
- modules/cloudtrail-baseline/variables.tf
- modules/config-baseline/README.md
- modules/ebs-baseline/README.md
- modules/guardduty-baseline/README.md
- modules/iam-baseline/README.md
- modules/secure-bucket/README.md
- modules/securityhub-baseline/README.md
- modules/vpc-baseline/README.md
- variables.tf
The original implementation has issue that causes an error when the insight type was set to null.
Enabling it by default would be just simpler since logging insights event doesn't seem to introduce too much cost in addition to the normal CloudTrail logging.
Note: Using a dynamic block would work if we want the insight event logging to be optional.
> feat: enable Insights event logging by default

- guardduty_baselines.tf
- variables.tf
In this pull request I added functionality to manualy enable or disable usage of a guardduty-baseline module. When calling terraform-aws-secure-baseline module set guardduty_enabled argument to true/false.
Default value of parameter guardduty_enabled is set to true.
> feat: Add functionality to manually enable/disable guardduty-baseline module

- modules/vpc-baseline/main.tf
- modules/vpc-baseline/versions.tf
The `aws_default_subnet` resources will only be created for existing VPC default subnets. This will fix `Default subnet not found` errors when one or multiple default subnets do not exist in the VPC. Fixes #198
Notes: 
* This requires bumping the aws provider minimum version to 3.55.0 to add support for [`aws_subnets` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnets). 
* Since this change uses `for_each` instead of `count`, the `aws_default_subnet` resources will be recreated using subnet ids instead of indexes.
> [vpc-baseline] Apply default subnet changes to existing subnets

- modules/vpc-baseline/README.md
- modules/vpc-baseline/main.tf
To keep `aws_subnets.default` being a known value before apply.
Refs: https://www.terraform.io/docs/language/meta-arguments/for_each.html#limitations-on-values-used-in-for_each
> fix: remove `aws_default_vpc` dependency

- modules/vpc-baseline/main.tf
Rollback this change since it causes redundant resource re-creations.
> refactor: remove `destination_options`
