- README.md
- compliance.md
- Update the reference to v1.2.0 benchmark
- Add a compliance status table
> CIS Amazon Web Services Foundations Benchmark v1.2.0

- config_baselines.tf
Otherwise Config recorder will only be able to write to S3 and will show "exception posting to the SNS topic".
> Add policy to allow publication to SNS topic

- guardduty_baselines.tf
See https://aws.amazon.com/about-aws/whats-new/2018/03/amazon-guardduty-now-available-in-europe-paris-region/
> feat: enable GuardDuty in Paris region.

- README.md
- compliance.md
- config_baselines.tf
- examples/root-example/main.tf
- examples/root-example/regions.tf
- guardduty_baselines.tf
- modules/vpc-baseline/main.tf
- outputs.tf
- providers.tf
- vpc_baselines.tf
Add a support for eu-north-1 region. Note that GuardDuty is not supported yet.
> Support eu-north-1 region

- README.md
- main.tf
- modules/securityhub-baseline/README.md
- modules/securityhub-baseline/main.tf
> feat: enable SecurityHub and CIS standard subscription

- .pre-commit-config.yaml
- README.md
- modules/alarm-baseline/README.md
- modules/cloudtrail-baseline/README.md
- modules/config-baseline/README.md
- modules/guardduty-baseline/README.md
- modules/iam-baseline/README.md
- modules/secure-bucket/README.md
- modules/securityhub-baseline/README.md
- modules/vpc-baseline/README.md
> enable terraform_docs hook

- config_baselines.tf
- modules/config-baseline/README.md
- modules/config-baseline/main.tf
- modules/config-baseline/variables.tf
Only include global resources in the main region.
> feat: only include global resources in the specified region

- config_baselines.tf
> recoder -> recorder

- README.md
- config_baselines.tf
- examples/select-region/main.tf
- examples/select-region/regions.tf
- examples/select-region/variables.tf
- examples/select-region/versions.tf
- guardduty_baselines.tf
- main.tf
- modules/config-baseline/README.md
- modules/config-baseline/main.tf
- modules/config-baseline/outputs.tf
- modules/config-baseline/variables.tf
- modules/guardduty-baseline/README.md
- modules/guardduty-baseline/main.tf
- modules/guardduty-baseline/outputs.tf
- modules/guardduty-baseline/variables.tf
- modules/vpc-baseline/README.md
- modules/vpc-baseline/main.tf
- modules/vpc-baseline/outputs.tf
- modules/vpc-baseline/variables.tf
- variables.tf
- vpc_baselines.tf
> feat: add an argument to specify target regions.

- config_baselines.tf
- guardduty_baselines.tf
See https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#01214-november-13-2019
> Fix deprecation warnings in Terraform >=0.12.14

- README.md
- examples/external-bucket/main.tf
- examples/organization/master/main.tf
- examples/organization/member/main.tf
- examples/select-region/main.tf
- examples/simple/main.tf
- main.tf
- modules/iam-baseline/main.tf
- modules/iam-baseline/variables.tf
- variables.tf
- allows assigning multiple users to the role
- allows passing an empty list, making the variable optional, closes:
https://github.com/nozaq/terraform-aws-secure-baseline/issues/75
> convert support_iam_role_principal_arn to a list

- README.md
> docs: fix a broken example link

- .pre-commit-config.yaml
- README.md
- main.tf
- modules/alarm-baseline/README.md
- modules/cloudtrail-baseline/README.md
- modules/cloudtrail-baseline/main.tf
- modules/cloudtrail-baseline/variables.tf
- modules/config-baseline/README.md
- modules/guardduty-baseline/README.md
- modules/iam-baseline/README.md
- modules/secure-bucket/README.md
- modules/securityhub-baseline/README.md
- modules/vpc-baseline/README.md
> fix: ensure to have the audit log bucket before CloudTrail

- modules/cloudtrail-baseline/README.md
- modules/cloudtrail-baseline/main.tf
- modules/cloudtrail-baseline/variables.tf
> feat: encrypt the sns topic

- main.tf
- modules/securityhub-baseline/README.md
- modules/securityhub-baseline/main.tf
- modules/securityhub-baseline/variables.tf
- securityhub.tf
> feat: enable SecurityHub in each region

- README.md
- modules/securityhub-baseline/README.md
- modules/securityhub-baseline/main.tf
- modules/securityhub-baseline/variables.tf
- securityhub.tf
- variables.tf
> New SecurityHub standards support

- modules/iam-baseline/README.md
- modules/iam-baseline/main.tf
- modules/iam-baseline/variables.tf
#114 
Let me know if I can improve something! 
Best!
> Make all roles to be optional

- README.md
- compliance.md
> docs: add the compliance status for AWS Foundational Security Best

- modules/vpc-baseline/main.tf
> feat: apply tags to default network resources

- bucket.tf
- modules/cloudtrail-baseline/main.tf
- modules/secure-bucket/main.tf
> Fix: deprecation warnings

- README.md
- modules/vpc-baseline/README.md
- modules/vpc-baseline/main.tf
- modules/vpc-baseline/variables.tf
- variables.tf
- vpc_baselines.tf
> feat: add a flag to enable/disable VPC Flow Logs

- modules/securityhub-baseline/README.md
- modules/securityhub-baseline/main.tf
- modules/securityhub-baseline/variables.tf
- securityhub.tf
> feat: associate members to master in SecurityHub

- .pre-commit-config.yaml
- README.md
- bucket.tf
- modules/iam-baseline/README.md
- modules/iam-baseline/variables.tf
- modules/vpc-baseline/main.tf
- variables.tf
- vpc_baselines.tf
> fix: invalid reference when flow logs is disabled

- modules/alarm-baseline/main.tf
- modules/alarm-baseline/variables.tf
This will allow enabling/disabling individual alarms.
Closes #162
> feat: allow enabling/disabling individual alarms

- vpc_baselines.tf
Currently, we have the VPC baseline disabled in one of our AWS accounts. When trying to update to the latest version of the module, we get several errors like this:
```
Error: Invalid index
on .terraform/modules/master_secure_baseline/vpc_baselines.tf line 395, in module "vpc_baseline_us-west-2":
395:   flow_logs_iam_role_arn      = local.is_cw_logs ? aws_iam_role.flow_logs_publisher[0].arn : null
├────────────────
aws_iam_role.flow_logs_publisher is empty tuple
The given key does not identify an element in this collection value.
```
Th condition for those modules is not using `var.vpc_enable` properly. This PR aims to fix that and simplify the conditions as well.
> Fix "Invalid index" error when VPC baseline is disabled

- modules/guardduty-baseline/main.tf
fix an issue for member accounts when applying #209
> fix: do not manage `datasources` in member accounts.

- README.md
- modules/alarm-baseline/README.md
- modules/alarm-baseline/variables.tf
- modules/config-baseline/README.md
- modules/config-baseline/variables.tf
> fix: make `sns_topic_kms_master_key_id` optional

- .gitignore
- .pre-commit-config.yaml
- chore: add validate pre-commit hook
- chore: update gitignore
> trivial clean ups

- modules/securityhub-baseline/README.md
- modules/securityhub-baseline/main.tf
- modules/securityhub-baseline/variables.tf
- securityhub_baselines.tf
> feat: enable finding aggregator in the main region

- modules/iam-baseline/variables.tf
- variables.tf
To conform to IAM.7 in AWS Foundational Security Best Practices.
> feat: enforce strong password policy by default

- README.md
- examples/external-bucket/main.tf
- examples/organization/master/main.tf
- examples/organization/member/main.tf
- examples/select-region/main.tf
- examples/simple/main.tf
- main.tf
- modules/alarm-baseline/README.md
- modules/alarm-baseline/versions.tf
- modules/analyzer-baseline/README.md
- modules/analyzer-baseline/versions.tf
- modules/cloudtrail-baseline/README.md
- modules/cloudtrail-baseline/versions.tf
- modules/config-baseline/README.md
- modules/config-baseline/versions.tf
- modules/ebs-baseline/README.md
- modules/ebs-baseline/versions.tf
- modules/guardduty-baseline/README.md
- modules/guardduty-baseline/versions.tf
- modules/securityhub-baseline/README.md
- modules/securityhub-baseline/versions.tf
- modules/vpc-baseline/README.md
- modules/vpc-baseline/versions.tf
to avoid the issue in terraform 1.1.3
https://github.com/hashicorp/terraform/issues/30326
> fix: set the minimum terraform version to 1.1.4

- modules/secure-bucket/main.tf
> feat: use S3 lifecycle rule V2

- docs/upgrade-1.0.md
> docs: add the missing import guidance

- modules/securityhub-baseline/main.tf
> feat: enable CIS benchmark v1.4.0 standard
